### ISSUE TITLE
Must Gather is not very robust

### ISSUE THREAD

**Issue by IanBoden** [ibm-mas/cli#476]
When the must gather runs any command failure during a script will cause the script to stop. For example collecting the pods if the container logs can't be read for a pod the script fails and does not collect any other pods. In the case seen it was that the pod had a container that was still initializing.

One option is to change:
`oc -n ${NAMESPACE} logs ${POD} -c ${CONTAINER} > ${APP_LOG_DIR}/${POD_NAME}_${CONTAINER}.log;`
to something like:

```
if [ ! oc -n ${NAMESPACE} logs ${POD} -c ${CONTAINER} > ${APP_LOG_DIR}/${POD_NAME}_${CONTAINER}.log ]
then
    echo "Problem reading container log" >> ${APP_LOG_DIR}/${POD_NAME}_${CONTAINER}.log
fi
```

Really what we would want is a try catch block in the loop so any problem with a single pod we could print an error message and just move on to the next, but that isn't really possible in bash and moving to python or another language would be quite a large effort.

**Comment by durera** [comment]
In the current version of the code on failure in various places we print a warning and continue:

```bash
      CONTAINERS=$(oc -n "${NAMESPACE}" get "${POD}" -o json -o jsonpath='{range .status.containerStatuses[*]}[{.name}] {end}' | tr -d '[]')
      for CONTAINER in ${CONTAINERS[@]}; do
        oc -n "${NAMESPACE}" logs "${POD}" -c "${CONTAINER}" &> "${APP_LOG_DIR}/${POD_NAME}_${CONTAINER}.log" || { echo_warning "  Error fetching logs for container ${CONTAINER} in pod $POD_NAME"; continue; }
      done
```
