### ISSUE TITLE
Command `mas mirror-images` results in playbook error

### ISSUE THREAD

**Issue by chriscochran** [ibm-mas/cli#539]
The Manage 8.7.0 CASE now includes image groups and a separately entitled add-on which result this playbook error:

`"error: unable to retrieve source image cp.icr.io/cp/manage/extension-icd manifest sha256:884cd4063a0369975743c9746831f4ab06deef915cc9a3e8790bb24e359d5fe0: denied: You are not authorized to access the specified resource. See https://cloud.ibm.com/docs/Registry?topic=Registry-troubleshoot-access-denied",
            "error: an error occurred during planning"`

When running the command `mas mirror-images` with `--mirror-manage` with Manage 8.7.

New capability in MAS-CLI is needed to handle image grouping and separately entitled resources. MAS-CLI should provide the image group and entitlement information to ansible-devops.

**Comment by chriscochran** [comment]
Related Issue: https://github.com/ibm-mas/ansible-devops/issues/1033

**Comment by durera** [comment]
I've fixed this as part of my other work.
